version: '3'
services:
  postgres:
    image: postgres:12.2-alpine
    tty: true
    restart: always
    volumes:
      - .db:/var/lib/postgresql/data
    stdin_open: true
    ports:
      - "44321:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tsundoku